import io
import hashlib
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def generate_cyber_pdf(report, analysis, user):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=50, leftMargin=50,
                            topMargin=50, bottomMargin=50)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='TitleLarge', alignment=1, fontSize=20, spaceAfter=15, fontName='Helvetica-Bold'))
    styles.add(ParagraphStyle(name='SectionHeader', fontSize=14, spaceAfter=10, spaceBefore=15, textColor=colors.HexColor('#005580'), fontName='Helvetica-Bold'))
    styles.add(ParagraphStyle(name='NormalText', fontSize=11, spaceAfter=8, leading=14))
    
    elements = []
    
    # Official Header
    elements.append(Paragraph("OFFICIAL CYBER CRIME FORENSIC REPORT", styles['TitleLarge']))
    elements.append(Paragraph(f"Report ID: {str(report.id)}", styles['NormalText']))
    elements.append(Paragraph(f"Date Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC", styles['NormalText']))
    elements.append(Spacer(1, 20))
    
    # Complainant Details
    elements.append(Paragraph("1. Complainant Details", styles['SectionHeader']))
    data_complainant = [
        ["Complainant Email", user.email],
        ["Report Filed On", report.created_at.strftime("%Y-%m-%d %H:%M:%S")],
        ["Platform/Source", report.platform],
        ["Offense Category", report.category]
    ]
    t_comp = Table(data_complainant, colWidths=[150, 350])
    t_comp.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 6)
    ]))
    elements.append(t_comp)
    
    # Incident Description
    elements.append(Paragraph("2. Description of Incident", styles['SectionHeader']))
    elements.append(Paragraph(report.description, styles['NormalText']))
    
    # Forensic AI Analysis
    elements.append(Paragraph("3. AI Forensic Analysis Details", styles['SectionHeader']))
    
    verdict = analysis.verdict or "Inconclusive"
    confidence = analysis.confidence_score or 0.0
    
    if verdict == "ai_generated":
        v_color = colors.red
    elif verdict == "human_made":
        v_color = colors.green
    else:
        v_color = colors.orange
        
    data_analysis = [
        ["Analysis ID", str(analysis.id)],
        ["File Name", analysis.original_filename or "N/A"],
        ["File Type", analysis.file_type.capitalize()],
        ["Analysis Verdict", verdict.replace("_", " ").upper()],
        ["Confidence Score", f"{confidence * 100:.2f}%"]
    ]
    t_ana = Table(data_analysis, colWidths=[150, 350])
    t_ana.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('TEXTCOLOR', (1, 3), (1, 3), v_color),
        ('FONTNAME', (1, 3), (1, 3), 'Helvetica-Bold')
    ]))
    elements.append(t_ana)
    
    elements.append(Spacer(1, 10))
    elements.append(Paragraph("Forensic Explanation:", styles['NormalText']))
    elements.append(Paragraph(analysis.explanation or "No detailed explanation available.", styles['NormalText']))
    
    # Evidence Hash & Certification
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("CERTIFICATION OF INTEGRITY", styles['SectionHeader']))
    elements.append(Paragraph("This document has been automatically generated by the Dictator AI Content Authenticity system. The cryptographic hash below verifies the integrity of this report at the time of generation.", styles['NormalText']))
    
    # Generate signature string for PDF display
    signature_base = f"{report.id}|{analysis.id}|{report.created_at.isoformat()}|{analysis.verdict}|{analysis.confidence_score}"
    pdf_hash = hashlib.sha256(signature_base.encode('utf-8')).hexdigest()
    
    elements.append(Paragraph(f"<b>Integrity Hash (SHA-256):</b><br/>{pdf_hash}", styles['NormalText']))
    
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("________________________________________", styles['NormalText']))
    elements.append(Paragraph("Authorized System Output - Dictator AI", styles['NormalText']))
    
    doc.build(elements)
    
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
