import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def generate_pdf_report(analysis, user):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='CenterTitle', alignment=1, fontSize=24, spaceAfter=20))
    styles.add(ParagraphStyle(name='Subtitle', fontSize=14, spaceAfter=10, textColor=colors.HexColor('#00d4ff')))
    
    elements = []
    
    # Title
    elements.append(Paragraph("Dictator AI Analysis Report", styles['CenterTitle']))
    elements.append(Spacer(1, 12))
    
    # File Details
    elements.append(Paragraph("Document Details", styles['Subtitle']))
    
    file_name = analysis.original_filename or "Text Input"
    file_type = analysis.file_type.capitalize()
    date_str = analysis.created_at.strftime("%Y-%m-%d %H:%M:%S")
    
    data = [
        ["File Name", file_name],
        ["Type", file_type],
        ["Analyzed On", date_str],
        ["User", user.email],
    ]
    
    t = Table(data, colWidths=[100, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))
    
    # Verdict Details
    elements.append(Paragraph("Analysis Verdict", styles['Subtitle']))
    
    verdict = analysis.verdict or "Inconclusive"
    verdict_display = verdict.replace("_", " ").title()
    confidence = analysis.confidence_score or 0.0
    
    # Color logic
    if verdict == "ai_generated":
        v_color = colors.red
    elif verdict == "human_made":
        v_color = colors.green
    else:
        v_color = colors.orange
        
    verdict_data = [
        ["Verdict", verdict_display],
        ["Confidence", f"{confidence * 100:.2f}%"]
    ]
    
    tv = Table(verdict_data, colWidths=[100, 300])
    tv.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('TEXTCOLOR', (1, 0), (1, 0), v_color),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (1, 0), (1, 1), 14),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    elements.append(tv)
    elements.append(Spacer(1, 20))
    
    # Explanation
    elements.append(Paragraph("Explanation", styles['Subtitle']))
    explanation = analysis.explanation or "No explanation provided."
    elements.append(Paragraph(explanation, styles['Normal']))
    
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("This report was automatically generated by Dictator AI Content Authenticity Detector.", styles['Normal']))
    
    doc.build(elements)
    
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
