"""
Token-Level Entropy Analysis — DetectGPT-inspired signal for AI text detection.

THEORY:
AI-generated text is produced by sampling from a language model's predicted
distribution. This means the actual tokens chosen tend to have HIGH probability
under a similar model (GPT-2). Human text, being generated by a fundamentally
different process (human cognition), produces tokens that are less predictable
— lower average log-probability and higher variance.

Key metrics:
- Mean log-probability: AI text → higher (less surprising)
- Log-prob standard deviation: AI text → lower (consistently unsurprising)
- Low-probability token ratio: AI text → fewer "surprise" tokens

This reuses the GPT-2 model already loaded by perplexity.py for zero extra
memory cost.
"""

import math
import numpy as np
import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

# Singleton — shared with perplexity.py if it loads first
_gpt2_model = None
_gpt2_tokenizer = None


def _load_gpt2():
    global _gpt2_model, _gpt2_tokenizer
    if _gpt2_model is None:
        print("Loading GPT-2 for entropy analysis...")
        _gpt2_tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
        _gpt2_model = GPT2LMHeadModel.from_pretrained("gpt2")
        _gpt2_model.eval()
    return _gpt2_tokenizer, _gpt2_model


def compute_entropy_scores(text: str) -> dict:
    """
    Compute token-level log-probability statistics.

    Returns:
        {
            "entropy_score": float 0-1 (higher = more likely AI),
            "mean_log_prob": float,
            "log_prob_std": float,
            "low_prob_ratio": float (fraction of tokens with log_prob < -5),
        }
    """
    tokenizer, model = _load_gpt2()

    encodings = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
    input_ids = encodings.input_ids

    if input_ids.size(1) < 5:
        return {
            "entropy_score": 0.5,
            "mean_log_prob": 0.0,
            "log_prob_std": 0.0,
            "low_prob_ratio": 0.5,
        }

    with torch.no_grad():
        outputs = model(input_ids)
        logits = outputs.logits  # (1, seq_len, vocab_size)

    # Shift: logits[t] predicts token at position t+1
    shift_logits = logits[:, :-1, :]  # (1, seq_len-1, vocab_size)
    shift_labels = input_ids[:, 1:]    # (1, seq_len-1)

    # Compute log-softmax to get log-probabilities
    log_probs_all = torch.log_softmax(shift_logits, dim=-1)  # (1, seq_len-1, vocab_size)

    # Gather the log-prob of the actual next token at each position
    token_log_probs = log_probs_all.gather(
        2, shift_labels.unsqueeze(-1)
    ).squeeze(-1).squeeze(0).numpy()  # (seq_len-1,)

    # Filter out any NaN/Inf
    token_log_probs = token_log_probs[np.isfinite(token_log_probs)]

    if len(token_log_probs) == 0:
        return {
            "entropy_score": 0.5,
            "mean_log_prob": 0.0,
            "log_prob_std": 0.0,
            "low_prob_ratio": 0.5,
        }

    mean_log_prob = float(np.mean(token_log_probs))
    log_prob_std = float(np.std(token_log_probs))

    # Low-probability tokens: log_prob < -5 means the model was very surprised
    # Human text has more of these
    low_prob_ratio = float(np.mean(token_log_probs < -5.0))

    # ---- Scoring ----
    # AI text: mean_log_prob typically -1.5 to -3.0 (high prob, low surprise)
    # Human text: mean_log_prob typically -3.5 to -6.0+ (lower prob, more surprise)
    # Sigmoid centered at -3.5 with steepness 1.5
    mean_score = 1.0 / (1.0 + math.exp(-1.5 * (mean_log_prob + 3.5)))

    # AI text: log_prob_std typically 1.5 to 2.5 (consistent)
    # Human text: log_prob_std typically 2.5 to 4.0+ (variable)
    # Sigmoid centered at 2.5 with steepness -1.5 (inverted: lower std → higher AI score)
    std_score = 1.0 / (1.0 + math.exp(1.5 * (log_prob_std - 2.5)))

    # AI text: low_prob_ratio typically 0.05 to 0.15
    # Human text: low_prob_ratio typically 0.20 to 0.50+
    # Sigmoid centered at 0.20 with steepness -10 (fewer surprise tokens → higher AI score)
    surprise_score = 1.0 / (1.0 + math.exp(10.0 * (low_prob_ratio - 0.20)))

    # Combine the three sub-signals
    entropy_score = 0.45 * mean_score + 0.30 * std_score + 0.25 * surprise_score

    return {
        "entropy_score": float(np.clip(entropy_score, 0.0, 1.0)),
        "mean_log_prob": mean_log_prob,
        "log_prob_std": log_prob_std,
        "low_prob_ratio": low_prob_ratio,
    }
